// <auto-generated />
namespace OnlineShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class ShowOnSiteIsAddedToItem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ShowOnSiteIsAddedToItem));
        
        string IMigrationMetadata.Id
        {
            get { return "202003121312587_ShowOnSiteIsAddedToItem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
