// <auto-generated />
namespace OnlineShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class ColorIdIsAddedToItem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ColorIdIsAddedToItem));
        
        string IMigrationMetadata.Id
        {
            get { return "202002151700299_ColorIdIsAddedToItem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
